# Generated by Django 3.2.5 on 2021-07-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210716_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
