# Generated by Django 3.2.5 on 2021-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_agenda_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='teste',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
