# Generated by Django 3.2.5 on 2021-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_agenda_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='asdfg',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
