# Generated by Django 3.2.5 on 2021-07-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_agenda_asdfg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='asdfg',
            new_name='asdf',
        ),
    ]
