# Generated by Django 3.2.5 on 2021-07-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_asdfg_agenda_asdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='asdf',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='teste',
            field=models.DateField(),
        ),
    ]
