# Generated by Django 3.2.5 on 2021-07-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210718_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='teste',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
