# Generated by Django 3.2.5 on 2021-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_agenda_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='teste',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
