# Generated by Django 3.2.5 on 2021-07-19 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_data_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='dataa',
            field=models.DateField(default=datetime.date.today, max_length=25),
        ),
        migrations.AddField(
            model_name='agenda',
            name='outro',
            field=models.CharField(default=None, max_length=18),
        ),
    ]
