# Generated by Django 3.2.5 on 2021-07-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210719_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='dataa',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='asdf',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='outro',
        ),
    ]
