# Generated by Django 3.2.5 on 2021-07-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_agenda_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='hour',
            field=models.TimeField(default=None),
        ),
    ]
