# Generated by Django 3.2.5 on 2021-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_agenda_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='information',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hour',
            field=models.TimeField(),
        ),
    ]
