# Generated by Django 3.2.5 on 2021-07-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210719_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='teste',
        ),
    ]
